@startuml VirtualNoe

!theme reddress-darkgreen

package Models
{
    interface IUser
    {
        + login() : String
        + password() : String
        + level() : Integer
        + money() : Integer
        + inventory() : IInventory
    }

    interface IInventory 
    { 
        + quantityOf(item : IItem) : Integer
        + ofType(type : IItem) : IItem[*]
    }

    interface IItem
    {
        + name() : String
        + use()
    }

    interface IFood implements IItem
    {
        /' number of points added to hunger gauge '/
        + calories() : Integer  
    }

    interface IBoost implements IItem
    {
        /' number of points added to stamina gauge '/
        + energy() : Integer
    }

    interface IDrug implements IItem
    {
        /' number of points added to life gauge '/
        + healing() : Integer
    }

    interface ICreature 
    { 
        + name() : String
        + life() : Integer
        + hunger() : Integer
        + stamina() : Integer
    }
}

package Controllers 
{ 
    class InventoryController
    {
        + add(item : IItem, amount : Integer) 
        + remove(item : IItem, amount : Integer)
        + show()
    }

    class UserController
    {
        /' TODO - see laravel scaffolding system (make:auth), etc. '/
    }

    class CreatureController
    {
        + feed(food : IFood)
        + boost(boost : IBoost)
        + heal(drug : IDrug)
    }
}

package Views 
{ 
    class MainLayout
    class SigninForm extends MainLayout   /' home, index '/
    class Game extends MainLayout   /' main game window '/
    {
        + callShowInventory()
    }
    class Documentation extends MainLayout   /' tutorial, etc. '/
}

/' RELATIONS '/
IUser" 1 " *--> " 1 "IInventory : - inventory
IInventory" 1 " o--> " * "IItem : - items
ICreature ..> IItem : use               /' TODO - not sure '/


/' MVC '/
Controllers ..> Models : modifies
Controllers ..> Views : updates
Views ..> Controllers : user interacts
Models ..> Controllers : notifies 

@enduml